### PR TITLE
changed # of eggs

### PR DESCRIPTION
**Pull request by stratkee**
Need test kitchen to test 5 eggs instead of 10 eggs.

### CODE REVIEW

**Comment by SeanIsTesting** [comment]
Tastes Egg-cellent !

**Comment by randehh213** [comment]
> Tastes Egg-cellent !

It's Eggceptional

**Comment by TheAmazingTKel** [comment]
5 eggs - really? I would recommend 12.

**Comment by SeanIsTesting** [comment]
12 seems egg-cessive

**Pull request merged**
